from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Email',
    'Message',
    'MessageRecipient',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'emails': 'Email',
    },
    'Email': {
        'user': 'User',
        'sentMessages': 'Message',
        'receivedMessages': 'MessageRecipient',
    },
    'Message': {
        'fromEmail': 'Email',
        'recipients': 'MessageRecipient',
    },
    'MessageRecipient': {
        'message': 'Message',
        'email': 'Email',
    },
}

# fmt: on