version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "[%(levelname)s] %(message)s"
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    mode: a
    encoding: utf-8

loggers:
  main_logger:
    level: DEBUG
    handlers: [console, file]
    propagate: no

